export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';

export const NAVER_CLIENT_SECRET = 'NAVER_CLIENT_SECRET';
export const KAKAO_CLIENT_SECRET = 'KAKAO_CLIENT_SECRET';
