#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

origin_url="<repo url>"

remote="$1"
url="$2"

if [ "$url" != "$origin_url" ]
then
    exit 0
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" == "main" -o "$current_branch" == "dev" -o "$current_branch" == "test" ]
then
    echo "do not push in dev or main branch"
    exit 1
fi

cd server && yarn lint && yarn test

exit 0