name: Backend Rest Server Deploy

on:
  push:
    branches: [main]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/rest

    steps:
      - name: repository의 파일을 가상 인스턴스로 복사합니다.
        uses: actions/checkout@v3

      - name: docker 관련 로직 처리를 위한 buildx를 설치합니다.
        uses: docker/setup-buildx-action@v2

      - name: docker hub에 로그인 합니다.
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: docker 이미지를 build 및 push합니다.
        uses: docker/build-push-action@v3
        with:
          context: ./backend/rest
          push: true
          tags: ${{ secrets.DOCKER_REST_IMAGE }}:${{ secrets.VERSION }},${{ secrets.DOCKER_REST_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-run:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: 배포 서버에서 docker image를 받아서 container를 실행시킵니다.
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.REST_SERVER_USER }}
          password: ${{ secrets.REST_SERVER_PWD }}
          host: ${{ secrets.REST_SERVER_HOST }}
          port: ${{ secrets.REST_SERVER_PORT }}

          script: |
            export CURRENT_CONTAINER=$(docker ps -aq -f "name=rest-server")
            docker stop $(echo $CURRENT_CONTAINER) && docker rm $(echo $CURRENT_CONTAINER)
            docker pull ${{ secrets.DOCKER_REST_IMAGE }}:latest
            docker rmi $(docker images -f "dangling=true" -q)
            docker run \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e JWT_ACCESS_TOKEN_SECRET=${{ secrets.JWT_ACCESS_TOKEN_SECRET }} \
            -e JWT_REFRESH_TOKEN_SECRET=${{ secrets.JWT_REFRESH_TOKEN_SECRET }} \
            -e NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
            -e KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
            -e CLIENT_ORIGIN_URL=${{ secrets.CLIENT_ORIGIN_URL }} \
            -e SWAGGER_USER=${{ secrets.SWAGGER_USER }} \
            -e SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }} \
            --name rest-server --restart always --network="host" -d -p 8080:8080 \
            ${{ secrets.DOCKER_REST_IMAGE }}:latest
